/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TugasBesar.User;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class Dashboard extends javax.swing.JFrame {

    DefaultTableModel model;
    boolean statusSimpan = true;

    Connection con;
    Statement perintah;
    ResultSet rs;
    String path2 = null;

    public Dashboard() {
        initComponents();
        model = (DefaultTableModel) table.getModel();
        con = TugasBesar.Admin.Database.getConnection();

        // Initialize the Statement object
        try {
            perintah = con.createStatement();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    this,
                    "Error initializing database connection",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    void clear() {
        NamaTf.setEnabled(false);
        HargaTf.setEnabled(false);
        NamaTf.setText("");
        HargaTf.setText("");
        inputfoto.setIcon(null);
    }

    void tampil() {
        try {
            // Step 4 Membuat Query
            String sql = "SELECT * FROM menu";
            model.setRowCount(0);  // Clear existing rows
            model.fireTableDataChanged();

            rs = perintah.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("nama_menu"),
                    rs.getString("harga")
                });
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Database tidak berhasil terkoneksi",
                    "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void updateTotal() {
        DefaultTableModel modelPesan = (DefaultTableModel) TablePesan.getModel();

        double total = 0;
        for (int i = 0; i < modelPesan.getRowCount(); i++) {
            Object subtotalObject = modelPesan.getValueAt(i, 3); // Assuming subtotal is in the fourth column
            if (subtotalObject != null) {
                total += (double) subtotalObject;
            }
        }

        Total.setText(String.valueOf(total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        inputfoto = new javax.swing.JLabel();
        NamaTf = new javax.swing.JTextField();
        HargaTf = new javax.swing.JTextField();
        JumlahPesan = new javax.swing.JSpinner();
        pesan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablePesan = new javax.swing.JTable();
        Total = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BatalPesan = new javax.swing.JButton();
        HapusPesanan = new javax.swing.JButton();
        Selesai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dashboard");
        setBackground(new java.awt.Color(246, 247, 235));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(246, 247, 235));

        jLabel37.setFont(new java.awt.Font("Futura Md BT", 0, 24)); // NOI18N
        jLabel37.setText("DineNear");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nama Menu", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.setBackground(new java.awt.Color(246, 247, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        inputfoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        inputfoto.setPreferredSize(new java.awt.Dimension(142, 78));

        NamaTf.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        NamaTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaTfActionPerformed(evt);
            }
        });

        HargaTf.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N

        pesan.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        pesan.setText("Pesan");
        pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamaTf, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(JumlahPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(HargaTf, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(inputfoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pesan)
                        .addGap(50, 50, 50))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NamaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HargaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JumlahPesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inputfoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TablePesan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Pesanan", "Harga", "Jumlah Pesanan", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablePesan);

        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel1.setText("Total");

        BatalPesan.setText("Batal Pesan");
        BatalPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalPesanActionPerformed(evt);
            }
        });

        HapusPesanan.setText("Hapus Pesanan");
        HapusPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusPesananActionPerformed(evt);
            }
        });

        Selesai.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        Selesai.setText("Selesai Memesan");
        Selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelesaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel37))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(HapusPesanan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BatalPesan)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)))
                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(BatalPesan)
                    .addComponent(HapusPesanan))
                .addGap(29, 29, 29)
                .addComponent(Selesai)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int selectedRow = table.getSelectedRow();
        if (selectedRow >= 0) {
            try {
                // Assuming that the 'foto' column is the fourth column in the table
                String nama = model.getValueAt(selectedRow, 0).toString(); // Assuming 'nama_menu' is in the first column
                NamaTf.setText(nama);

                if (model.getColumnCount() > 1) {
                    String harga = model.getValueAt(selectedRow, 1).toString(); // Assuming 'harga' is in the second column
                    HargaTf.setText(harga);
                } else {
                    // Handle the case where the model doesn't have a second column
                    // You may display a message, log an error, or take appropriate action
                    HargaTf.setText("N/A"); // Set a default value or handle it as needed
                }

                // Fetch the Blob directly from the database based on the 'id_Menu'
                String sql = "SELECT foto FROM menu WHERE nama_menu = ?";
                try (PreparedStatement pstmt = con.prepareStatement(sql)) {
                    pstmt.setString(1, nama);
                    try (ResultSet resultSet = pstmt.executeQuery()) {
                        if (resultSet.next()) {
                            Blob image = resultSet.getBlob("foto");

                            if (image != null) {
                                byte[] bytea = image.getBytes(1, (int) image.length());
                                try (FileOutputStream fos = new FileOutputStream("C:\\Users\\ACER\\OneDrive\\Documents\\Kuliah\\Semester 3\\Pemograman Visual\\PraktikumVisual3B\\src\\ImagesTugasBesar\\Menu\\download.jpg")) {
                                    fos.write(bytea);
                                } catch (IOException e) {
                                    e.printStackTrace(); // Handle IO exception
                                }

                                ImageIcon icon = new ImageIcon(bytea);
                                inputfoto.setIcon(icon);
                            }
                        }
                    }
                    JumlahPesan.setEnabled(true);
                    JumlahPesan.setValue(1);
                } catch (SQLException e) {
                    e.printStackTrace(); // Handle SQLException
                }
            } catch (Exception ex) {
                ex.printStackTrace(); // Handle other exceptions
            }
        }
    }//GEN-LAST:event_tableMouseClicked

    private void NamaTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaTfActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        NamaTf.setEnabled(false);
        HargaTf.setEnabled(false);
        JumlahPesan.setEnabled(false);

        tampil();  // Fetch data from the database and update the table model

        // Tambahkan MouseListener ke jTable1 dalam constructor atau method initUI kelas Anda
        table.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int selectedIndexRow = table.getSelectedRow();

                NamaTf.setText(model.getValueAt(selectedIndexRow, 0).toString());
                HargaTf.setText(model.getValueAt(selectedIndexRow, 1).toString());
            }
        });

    }//GEN-LAST:event_formWindowOpened

    private void pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanActionPerformed
        // TODO add your handling code here:
        String namaMenu = NamaTf.getText();
        String harga = HargaTf.getText();
        int jumlahPesan = (int) JumlahPesan.getValue();

        // Validasi agar jumlah pesan tidak kurang dari 1
        if (jumlahPesan < 1) {
            JOptionPane.showMessageDialog(this, "Jumlah pesanan harus lebih dari 0", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return; // Keluar dari method jika jumlah pesan kurang dari 1
        }

        // Calculate subtotal
        double subtotal = Double.parseDouble(harga) * jumlahPesan;

        // Add the selected item to the TablePesan table
        DefaultTableModel modelPesan = (DefaultTableModel) TablePesan.getModel();

        // Insert the new row at the beginning of the table
        modelPesan.insertRow(0, new Object[]{namaMenu, harga, jumlahPesan, subtotal});

        // Update the total field
        updateTotal();
    }//GEN-LAST:event_pesanActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalActionPerformed

    private void HapusPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusPesananActionPerformed
        // TODO add your handling code here:
        int selectedRow = TablePesan.getSelectedRow();
        if (selectedRow >= 0) {
            DefaultTableModel modelPesan = (DefaultTableModel) TablePesan.getModel();
            modelPesan.removeRow(selectedRow);

            // Update total setelah menghapus pesanan
            updateTotal();
        } else {
            JOptionPane.showMessageDialog(this, "Pilih pesanan yang akan dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_HapusPesananActionPerformed

    private void BatalPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalPesanActionPerformed
        // TODO add your handling code here:
        // Batal pesanan dengan mengosongkan TablePesan
        DefaultTableModel modelPesan = (DefaultTableModel) TablePesan.getModel();
        modelPesan.setRowCount(0);

        // Update total setelah membatalkan pesanan
        updateTotal();
    }//GEN-LAST:event_BatalPesanActionPerformed

    private void SelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelesaiActionPerformed
        // TODO add your handling code here:
        // Cek apakah ada pesanan dalam tabel
        if (TablePesan.getRowCount() > 0) {
            JOptionPane.showMessageDialog(this,
                    "Silakan segera membayar di kasir sebelum makanan dihidangkan.",
                    "Pembayaran di Kasir",
                    JOptionPane.INFORMATION_MESSAGE);

            // Setelah proses pengiriman pesanan, kosongkan tabel pesanan
            DefaultTableModel modelPesan = (DefaultTableModel) TablePesan.getModel();
            modelPesan.setRowCount(0);

            // Update total setelah mengosongkan pesanan
            updateTotal();

            // Kosongkan data pada inputan
            clear();
        } else {
            JOptionPane.showMessageDialog(this, "Tidak ada pesanan untuk dihidangkan.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_SelesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BatalPesan;
    private javax.swing.JButton HapusPesanan;
    private javax.swing.JTextField HargaTf;
    private javax.swing.JSpinner JumlahPesan;
    private javax.swing.JTextField NamaTf;
    private javax.swing.JButton Selesai;
    private javax.swing.JTable TablePesan;
    private javax.swing.JTextField Total;
    private javax.swing.JLabel inputfoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton pesan;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
