/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TugasBesar.User;

import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class Login extends javax.swing.JFrame {

    Connection conn;
    Statement stat;
    ResultSet rs;
    String sql;

    //Deklarasi konstruktor tanpa parameter yang bersifat publik
    public Login() {
        initComponents(); //Pemanggilan metode initComponents() untuk menginisialisasi komponen GUI

        try { //Blok try dimulai untuk menangani pengecualian
            conn = Database.getConnection(); //Memanggil metode getConnection() dari kelas Database untuk mendapatkan objek koneksi
            stat = conn.createStatement(); //Memanggil metode createStatement() dari objek koneksi untuk mendapatkan objek statement
        } catch (SQLException e) { //Menangani pengecualian SQLException jika terjadi
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e); //Menggunakan Logger untuk mencatat informasi pengecualian ke log dengan tingkat SEVERE

        }

        Icon i = jLabel1.getIcon();
        ImageIcon icon = (ImageIcon) i;
        Image image = icon.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        jLabel1.setIcon(new ImageIcon(image));

    }

    /**
     * Creates new form Login
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelKiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelKanan = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();
        UnLabel = new javax.swing.JLabel();
        PwLabel = new javax.swing.JLabel();
        UnField = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        PwField = new javax.swing.JPasswordField();
        DhaLabel = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LOGIN MENU");
        setBackground(new java.awt.Color(183, 222, 210));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelKiri.setBackground(new java.awt.Color(246, 247, 235));
        PanelKiri.setPreferredSize(new java.awt.Dimension(360, 512));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesTugasBesar/Secure login-amico - Copy.png"))); // NOI18N

        javax.swing.GroupLayout PanelKiriLayout = new javax.swing.GroupLayout(PanelKiri);
        PanelKiri.setLayout(PanelKiriLayout);
        PanelKiriLayout.setHorizontalGroup(
            PanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKiriLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        PanelKiriLayout.setVerticalGroup(
            PanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKiriLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );

        getContentPane().add(PanelKiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        PanelKanan.setBackground(new java.awt.Color(246, 247, 235));
        PanelKanan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        PanelKanan.setPreferredSize(new java.awt.Dimension(360, 512));

        LoginLabel.setFont(new java.awt.Font("Futura Md BT", 0, 32)); // NOI18N
        LoginLabel.setText("LOGIN");

        UnLabel.setFont(new java.awt.Font("Futura Md BT", 0, 16)); // NOI18N
        UnLabel.setText("Username");

        PwLabel.setFont(new java.awt.Font("Futura Md BT", 0, 16)); // NOI18N
        PwLabel.setText("Password");

        UnField.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N

        LoginButton.setFont(new java.awt.Font("Futura Md BT", 0, 16)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        PwField.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        PwField.setPreferredSize(new java.awt.Dimension(6, 22));

        DhaLabel.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        DhaLabel.setText("Don't have account?");

        registerButton.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        jLabel2.setText("Sign In to your account");

        javax.swing.GroupLayout PanelKananLayout = new javax.swing.GroupLayout(PanelKanan);
        PanelKanan.setLayout(PanelKananLayout);
        PanelKananLayout.setHorizontalGroup(
            PanelKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKananLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(PanelKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PwLabel)
                    .addComponent(UnLabel)
                    .addComponent(UnField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(LoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PwField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelKananLayout.createSequentialGroup()
                        .addComponent(DhaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKananLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKananLayout.createSequentialGroup()
                        .addComponent(LoginLabel)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKananLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(109, 109, 109))))
        );
        PanelKananLayout.setVerticalGroup(
            PanelKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKananLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(LoginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addComponent(UnLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UnField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PwLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PwField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(LoginButton)
                .addGap(47, 47, 47)
                .addGroup(PanelKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DhaLabel)
                    .addComponent(registerButton))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getContentPane().add(PanelKanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        this.setVisible(false); //agar halaman login tertutup ketika menekan button register
        new Register().setVisible(true); //memunculukan halaman register
    }//GEN-LAST:event_registerButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        try {
            sql = "SELECT * FROM user WHERE username='" + UnField.getText() + "' AND password='" + PwField.getText() + "'"; //Membuat query SQL untuk mengambil data user berdasarkan username dan password yang diinputkan
            rs = stat.executeQuery(sql); //Mengeksekusi query dan menyimpan hasilnya dalam objek ResultSet
            if (rs.next()) { //Memeriksa apakah ada hasil dari query
                //Memeriksa apakah username dan password yang diinputkan sesuai dengan data dari database
                if (UnField.getText().equals(rs.getString("username")) && Arrays.equals(PwField.getPassword(), rs.getString("password").toCharArray())) {
                    JOptionPane.showMessageDialog(null, "berhasil login"); //Menampilkan pesan sukses jika login berhasil
                    this.setVisible(false);  //agar halaman login tertutup berhasil login
                    new Dashboard().setVisible(true); //memunculkan halaman dashboard
                }
            } else {
                //Menampilkan pesan error jika username atau password tidak sesuai
                JOptionPane.showMessageDialog(null, "Username atau Password yang anda masukkan salah"); //Menampilkan pesan Gagal jika login Gagal
            }
        } catch (Exception e) {
            //Menangani pengecualian dan menampilkan pesan error
            JOptionPane.showMessageDialog(this, "Error in database operation: " + e.getMessage());
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DhaLabel;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JPanel PanelKanan;
    private javax.swing.JPanel PanelKiri;
    private javax.swing.JPasswordField PwField;
    private javax.swing.JLabel PwLabel;
    private javax.swing.JTextField UnField;
    private javax.swing.JLabel UnLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables
}
